### ISSUE TITLE
Hey, the readme specified the Python Plugin Manager in Configure Krita Settings

### ISSUE THREAD

**Issue by watercolorhearts** [abeimler/krita-plugin-durra#1]
And I don't see it in Krita 4.0.1, where it is located?

**Comment by abeimler** [comment]
The `Python Plugin Manager` should be there.

> Settings ‣ Configure Krita ‣ Python Plugin Manager  
https://docs.krita.org/en/user_manual/python_scripting/introduction_to_python_scripting.html

![bildschirmfoto_2018-08-10_00-16-40](https://user-images.githubusercontent.com/22779737/43929026-c0b58ab0-9c22-11e8-9ed2-1be0f087b60f.png)
